# Generated by Django 4.2.8 on 2024-01-02 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('News', '0002_news_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsClick',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('editorId', models.IntegerField()),
                ('type', models.IntegerField()),
                ('clickNumber', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='news',
            name='type',
            field=models.IntegerField(default=1),
        ),
    ]
